# Generated by Django 6.1.1 on 2026-09-11 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('url_base', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=255)),
                ('empresa', models.CharField(max_length=255)),
                ('descricao_bruta', models.TextField()),
                ('url', models.URLField()),
                ('nivel', models.CharField(choices=[('junior', 'Júnior'), ('pleno', 'Pleno'), ('senior', 'Sênior'), ('nao_informado', 'Não informado')], default='nao_informado', max_length=20)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('coletado_em', models.DateTimeField(auto_now_add=True)),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='vagas.fonte')),
            ],
            options={
                'unique_together': {('fonte', 'id_externo')},
            },
        ),
    ]
