# Generated by Django 6.1.1 on 2026-09-11 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='basico', max_length=20)),
                ('skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='skills.skill')),
            ],
        ),
    ]
