# Generated by Django 6.1.1 on 2026-09-13 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('quero_aplicar', 'Quero aplicar'), ('aplicado', 'Aplicado'), ('entrevista', 'Em entrevista'), ('recusado', 'Recusado'), ('aceito', 'Aceito')], default='quero_aplicar', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('vaga', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidatura', to='vagas.vaga')),
            ],
        ),
    ]
