# Generated by Django 6.1.1 on 2026-09-11 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_normalizado', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VagaSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencias', models.PositiveIntegerField(default=1)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas_relacionadas', to='skills.skill')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_encontradas', to='vagas.vaga')),
            ],
            options={
                'unique_together': {('vaga', 'skill')},
            },
        ),
    ]
